# Generated by Django 4.2.3 on 2023-07-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=130, null=True, unique=True),
        ),
    ]
