# Generated by Django 4.2.3 on 2023-07-18 18:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='PublisherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Publisher',
                'verbose_name_plural': 'Publishers',
                'db_table': 'publishers',
            },
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=130, unique=True)),
                ('model', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('main_image', models.ImageField(upload_to='images/product_detail')),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('like', models.PositiveIntegerField(default=0)),
                ('availability', models.BooleanField(default=True)),
                ('installment', models.BooleanField(default=False)),
                ('isbn', models.CharField(max_length=50, unique=True)),
                ('pages', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('cover', models.CharField(choices=[('soft', 'Мягкая'), ('hard', 'Твёрдая'), ('softwithslipcase', 'Мягкая + Футляр')], default='soft', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.authormodel')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'books',
            },
        ),
    ]
