# Generated by Django 4.2.3 on 2023-07-24 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_brandmodel_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandmodel',
            options={'ordering': ('name',), 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
    ]
