# Generated by Django 4.2.3 on 2023-07-22 06:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=130, null=True, unique=True)),
                ('model', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('main_image', models.ImageField(upload_to='images/product_detail')),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('like', models.PositiveIntegerField(default=0)),
                ('availability', models.BooleanField(default=True)),
                ('installment', models.IntegerField(blank=True, choices=[('6', '6 months'), ('12', '12 months')], default='12', null=True)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Big Product',
                'verbose_name_plural': 'Big Products',
                'db_table': 'big_products',
            },
        ),
    ]
