# Generated by Django 4.2.3 on 2023-07-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big_products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigproductmodel',
            name='installment',
            field=models.BooleanField(default=False),
        ),
    ]
