# Generated by Django 4.2.3 on 2023-07-23 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('big_products', '0003_alter_bigproductmodel_installment'),
        ('eav', '0010_alter_attribute_id_alter_enumgroup_id_and_more'),
        ('details', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacteristicsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eav.attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='big_products.bigproductmodel')),
            ],
            options={
                'verbose_name': 'Characteristic',
                'verbose_name_plural': 'Characteristics',
                'db_table': 'characteristics',
            },
        ),
    ]
