# Generated by Django 4.2.3 on 2023-07-18 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountmodel',
            options={'verbose_name': 'Discount', 'verbose_name_plural': 'Discounts'},
        ),
        migrations.AlterModelOptions(
            name='reviewmodel',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelTable(
            name='discountmodel',
            table='discounts',
        ),
        migrations.AlterModelTable(
            name='reviewmodel',
            table='reviews',
        ),
    ]
