# Generated by Django 4.2.3 on 2023-07-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_alter_discountmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=130, null=True, unique=True),
        ),
    ]
